# FIXME: Patch triagebot to support `notify-zulip.<label>` getting mapped to an array of actions.
#        At the moment, the beta-nominated+T-rustdoc action fully occupies the beta-nominated slot
#        preventing others from adding more beta-nominated actions.
[notify-zulip."beta-nominated"]
required_labels = ["T-rustdoc"]
zulip_stream = 266220 # #t-rustdoc
topic = "beta-nominated: #{number}"
message_on_add = "PR #{number}'s beta-nomination has been added. T-rustdoc"
message_on_remove = "PR #{number}'s beta-nomination has been removed. T-rustdoc"
message_on_close = "PR #{number} has been closed. Thanks for participating! T-rustdoc"
message_on_reopen = "PR #{number} has been reopened. Pinging @*T-rustdoc*. T-rustdoc"




[notify-zulip."beta-nominated".compiler]
required_labels = ["T-compiler"]
zulip_stream = 266221
topic = "beta-nominated: #{number}"
message_on_add = "PR #{number}'s beta-nomination has been added. T-compiler"
message_on_remove = "PR #{number}'s beta-nomination has been removed. T-compiler"
message_on_close = "PR #{number} has been closed. Thanks for participating! T-compiler"
message_on_reopen = "PR #{number} has been reopened. Pinging @*T-rustdoc*. T-compiler"











[notify-zulip."beta-nominated".miri]
required_labels = ["T-miri"]
zulip_stream = 266222
topic = "beta-nominated: #{number}"
message_on_add = "PR #{number}'s beta-nomination has been added. T-miri"
message_on_remove = "PR #{number}'s beta-nomination has been removed. T-miri"
message_on_close = "PR #{number} has been closed. Thanks for participating! T-miri"
message_on_reopen = "PR #{number} has been reopened. Pinging @*T-rustdoc*. T-miri"
